name: distribute_cli
description: "Quick way to distribute your app to playstore and appstore"
version: 1.0.0
homepage: https://github.com/nizwar/distribute_cli.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  args: ^2.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
