name: distribute_cli
description: "Quick way to distribute your app to playstore and appstore"
version: 2.8.1
homepage: https://github.com/nizwar/distribute_cli.git
repository: https://github.com/nizwar/distribute_cli.git
issue_tracker: https://github.com/nizwar/distribute_cli/issues
topics:
  - cli
  - flutter
  - deployment
  - ci

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  args: ^2.7.0
  basic_utils: ^5.8.2
  crypto: ^3.0.0
  dio: ^5.9.2
  path: ^1.9.1
  yaml: ^3.1.3
  yaml_codec: ^1.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0

executables:
  distribute: distribute_cli
