name: distribute_cli
description: "Quick way to distribute your app to playstore and appstore"
version: 2.2.0
homepage: https://github.com/nizwar/distribute_cli.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  args: ^2.7.0
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  yaml: ^3.1.3
  yaml_codec: ^1.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

executables:
  distribute: distribute_cli
